version: "3.9"

services:
  db:
    image: postgres:16
    container_name: saltseer_postgres
    restart: always
    environment:
      POSTGRES_DB: saltseer
      POSTGRES_USER: saltseer
      POSTGRES_PASSWORD: saltseer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  salt-master:
    image: saltstack/salt:latest
    container_name: saltseer_master
    command: salt-master -l info
    ports:
      - "4505:4505"
      - "4506:4506"

  salt-minion:
    image: saltstack/salt:latest
    container_name: saltseer_minion
    command: salt-minion -l info
    depends_on:
      - salt-master

volumes:
  postgres_data:

